### PR TITLE
A  pseudo PR about formatting

### PR DESCRIPTION
**Pull request by tenheadedlion**
Want to hear your opinions about the `rustfmt.toml`

Last week we talked about Rust code formatting, so I did some brief research on that, I looked into some famous codebases, here is what I found:

- Zero configuration
    - tokio: https://github.com/tokio-rs/tokio
- minimalist style
    - https://github.com/briansmith/ring/blob/main/rustfmt.toml
- Polkadot style
    - https://github.com/paritytech/polkadot/blob/master/rustfmt.toml
    - https://github.com/paritytech/substrate/blob/master/rustfmt.toml
- heavy
    - https://github.com/paritytech/subxt/blob/master/.rustfmt.toml

My thoughts:
1. if we are going to do this, we have to think about what will happen to the old code previously written
    - possible solutions:
       - when it comes to editing existing code, first format it and make a commit, then add new content
       - apply the formatting to the whole project in one commit
2. we should follow the Polkadot style
    - with the following exceptions:
        - no tabs for indentation
        - maximum line width should be 80, best for double panel editing on a 27-inch screen, with no code overflowing to the right

### CODE REVIEW

**Comment by tenheadedlion** [comment]
we can use git hooks to enforce formatting checking, but git hooks are local scripts, to distribute them requires extra initializing scripts, a Makefile is a proper choice. In regard to hook management, we can use https://pre-commit.com/ or write our own. the last commit contains the configuration of `pre-commit`, a file that violates the formatting rule will trigger errors like this:

```shell
$  git commit -m "some comment"
fmt......................................................................Failed
- hook id: fmt
- exit code: 1

[cdylib (2021)] "/home/test/repo/contracts/semi-bridge/src/lib.rs"
[lib (2021)] "/home/test/repo/index/src/lib.rs"
rustfmt --edition 2021 --check index/src/v0/executors/dex_executor.rs index/src/v0/executors/mod.rs /home/test/repo/contracts/semi-bridge/src/lib.rs /home/test/repo/index/src/lib.rs
Diff in /home/test/repo/index/src/v0/executors/dex_executor.rs at line 1:
-pub struct StubExecutor { name: String, }
+pub struct StubExecutor {
+    name: String,
+}
 
Diff in /home/test/repo/index/src/v0/executors/dex_executor.rs at line 1:
-pub struct StubExecutor { name: String, }
+pub struct StubExecutor {
+    name: String,
+}
 
Diff in /home/test/repo/index/src/v0/executors/dex_executor.rs at line 1:
-pub struct StubExecutor { name: String, }
+pub struct StubExecutor {
+    name: String,
+}
```

**Comment by tenheadedlion** [comment]
Alternatively, we can use rust libraries for the formatting purpose, like this one: https://github.com/swellaby/rusty-hook, the disadvantage of this method is that we have to add `rusty-hook` to every `Cargo.toml`. We can't add it directly to the root cargo.toml if our projects are managed as workspaces

**Comment by kvinwang** [comment]
> possible solutions:
> * when it comes to editing existing code, first format it and make a commit, then add new content
> * apply the formatting to the whole project in one commit

We are currently following the first approach. I think we can do the second when someday there isn't any big PR on the way.



> we should follow the Polkadot style
> * with the following exceptions:
>   
>   * no tabs for indentation
>   * maximum line width should be 80, best for double panel editing on a 27-inch screen, with no code overflowing to the right

I am not a fan of 80 columns limit. It's an old rule that comes from the days people work with fixed-width terminals. In modern editors, the 80-column styled code looks ugly. Even if it can display better on the v-splited pannel on 27-inch screens, it wouldn't look better on other-sized screens. The GitHub review page on my 13.3 inch MBP for example: 
image.


For some other items in the `rustfmt.toml`:

- use_small_heuristics = "Max"
I don't think we should overwrite the "Default" to "Max". Because the "Default" means:

  [fn_call_width](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#fn_call_width) - 60%
  [attr_fn_like_width](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#attr_fn_like_width) - 70%
  [struct_lit_width](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#struct_lit_width) - 18%
  [struct_variant_width](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#struct_variant_width) - 35%
  [array_width](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#array_width) - 60%
  [chain_width](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#chain_width) - 60%
  [single_line_if_else_max_width](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#single_line_if_else_max_width) - 50%

  Looks like changing to "Max" would make some of them, like struct literals, look ugly.

- imports_granularity = "Crate"
  This one looks good. However, the option is unstable yet (And there are some other options in the file that are also unstable). Looks like our `pruntime`, `phala-node` and `pherry` would be able to be compiled with stable Rust from `1.65`. We might want to switch to the stable toolchain someday after the `1.65` is released. If it happens, it would not be that convenient for developers to format the code with these nightly options.

- use_field_init_shorthand = true
  We should set it to true. The doc says it defaults to `false`. However, in my past experience, it always use shorthand. I am not sure if it really defaults to false. Anyway, the clippy also covers this checking. So I think we can feel free to keep it to default.

All other options in the `rustfmt.toml` look good to keep it default. So, I think it might be OK to choose the zero-config way.

**Comment by kvinwang** [comment]
> we can use git hooks to enforce formatting checking, but git hooks are local scripts, to distribute them requires extra initializing scripts, a Makefile is a proper choice.

We enforce it in the CI and let people choose their favorite solution in their local dev environment.

**Comment by tenheadedlion** [comment]
Thanks for the elaboration, that just pointed out something I was not aware of.

> We can enforce it in the CI and let people choose their favorite solution in their local dev environment.

I agree with this, with an enforced `rustfmt.toml` it will be inconvenient for us to use our own formatting style in localhost, and `pre-commit` can make the repo and the process of committing look ugly. And I personally don't like customing things.

To be clear, we are not doing the `rustfmt.toml` at all?  We will not have an explicit `rustfml.toml` in the project, instead, we will run `cargo fmt` without a `rustfmt.toml` in CI, do I understand it right?

**Comment by kvinwang** [comment]
> To be clear, we are not doing the `rustfmt.toml` at all? We will not have an explicit `rustfml.toml` in the project, and we will run `cargo fmt` without a `rustfmt.toml` in CI, do I understand it right?

If it won't convert `A { a }` to `A { a: a }` with the default setting of `use_field_init_shorthand`, I think it's OK to run `cargo fmt` without a `rustfmt.toml`. I am not very sure about the behavior of use_field_init_shorthand, could you have a try?

**Comment by tenheadedlion** [comment]
@kvinwang I just tried it out with this piece of code:

```rust
struct Foo {
    x: u32,
    y: u32,
    z: u32,
}

fn _test() {
    let x = 1;
    let y = 2;
    let z = 3;
    let _a = Foo { x, y, z };
    let _b = Foo { x: x, y: y, z: z };
}
```
Here is the result:

- If I don't use a `rustfmt.toml`, then running `cargo fmt` change nothing
- If I set `use_field_init_shorthand = false` in the `rustfmt.toml`, nothing changes either
- If I set `use_field_init_shorthand = true` in the `rustfmt.toml`, then the last line is changed to `let _b = Foo { x, y, z };`

So if we don't use a `rustfmt.toml`, `cargo fmt` doesn't seem to change the field initializers.

Let me setup a CI later, to see how it goes.

**Comment by tenheadedlion** [comment]
Also, I think we can do all kinds of experiments on this new project. If you have any new ideas about code style, please don't hesitate to bring them up.

**Review by tolak — COMMENTED** [review]
I suggest we can have a dedicated rust template repo so that we can discuss and experiment with format stuff on there. For InDex, it's better just to have the final solution here.

**Comment by kvinwang** [comment]
> Here is the result:
> 
> * If I don't use a `rustfmt.toml`, then running `cargo fmt` change nothing
> * If I set `use_field_init_shorthand = false` in the `rustfmt.toml`, nothing changes either
> * If I set `use_field_init_shorthand = true` in the `rustfmt.toml`, then the last line is changed to `let _b = Foo { x, y, z };`
> 
> So if we don't use a `rustfmt.toml`, `cargo fmt` doesn't seem to change the field initializers.
> 
> Let me setup a CI later, to see how it goes.

So, we can keep the `rustfmt.toml` with only `use_field_init_shorthand = true` in it, or without a `rustfmt.toml`. Both sound OK to me.

Without the option `use_field_init_shorthand = true` set, the field init style can still be checked by `cargo clippy`.

We can set up `cargo fmt` and `cargo clippy` in the CI first and do more config in the future if it is necessary.

**Comment by tenheadedlion** [comment]
moved to https://github.com/Phala-Network/index-contract/pull/4

**Pull request closed without merging**
