### PR TITLE
Add CI workflows

### PR DESCRIPTION
**Pull request by tenheadedlion**
4 jobs are added to the workflows:

## cargo test

applied to both `contracts/` and `index/`

## cargo clippy

currently only applied to `index`. Can't apply it to `contracts`, ink! will trigger errors that don't make sense:

```shell
error: this let-binding has unit value
   --> contracts/semi-bridge/src/lib.rs:112:83
    |
112 |         pub fn transfer(&self, token_rid: H256, amount: U256, recipient: H256) -> Result<()> {
    |                                                                                   ^^^^^^^^^^ help: omit the `let` binding: `Result<()>;`
```

## cargo fmt -- --check

applied to all rust code. `rustfmt.toml` has only one configuration entry: `use_field_init_shorthand = true`. 

example output: https://github.com/tenheadedlion/index-contract/actions/runs/3378290152/jobs/5608299981#step:5:7

```shell
Run cargo fmt --all -- --check
Diff in /home/runner/work/index-contract/index-contract/index/src/transactors/sub_transactors.rs at line 9:
     let y = 2;
     let z = 3;
     let _a = Foo { x, y, z };
-    let _b = Foo { x: x, y: y, z: z };
+    let _b = Foo { x, y, z };
 }
 
Error: Process completed with exit code 1.
```

## cargo contract check

Sometimes contract packages can pass `cargo test` but fail on `cargo contract check`, so it's necessary to run this test

however the test is time-consuming, so it only runs on pull requests that target the `main` branch

```yaml
on:
  pull_request:
    branches:
      - "main"
```

for more example outputs check this out: https://github.com/tenheadedlion/index-contract/actions

### CODE REVIEW

**Comment by kvinwang** [comment]
> ```shell
> error: this let-binding has unit value
>    --> contracts/semi-bridge/src/lib.rs:112:83
>     |
> 112 |         pub fn transfer(&self, token_rid: H256, amount: U256, recipient: H256) -> Result<()> {
>     |  
> ```

We may use `cargo clippy -- --allow clippy::let_unit_value` as a workaround for contracts.

> Sometimes contract packages can pass `cargo test` but fail on `cargo contract check`, so it's necessary to run this test

How about running`cargo check` to the whole workspace and `cargo contract build` rather than `cargo contract check` to contracts?
Because passing `cargo contract check` doesn't mean it can build.

**Comment by tenheadedlion** [comment]
@kvinwang I just changed cargo clippy test config to this:

```yml
      - name: Run cargo clippy for index
        run: cd index/ && cargo clippy --all-targets -- -D warnings
      - name: Run cargo clippy for contracts
        run: cargo clippy -- --allow clippy::let_unit_value -D warnings
```

the reason to run 2 clippy separately is that `index/` is not a member of the root `Cargo.toml`

```
members = [
    "contracts/semi-bridge",
]

exclude = [
    "index",
]
```

if we include `index` as a member, then we can not compile contracts via `cargo contract build`, here's a sample output:

```
 [2/5] Building cargo project
2022-11-03T05:27:06.827330Z  INFO cargo_contract::util: Invoking cargo: "/home/root_/.rustup/toolchains/nightly-2022-10-25-x86_64-unknown-linux-gnu/bin/cargo" "build" "--target=wasm32-unknown-unknown" "-Zbuild-std" "--no-default-features" "--release" "--target-dir=/home/root_/Workspace4/index-contract-official/target/ink/semi_bridge" "--features=ink_env/ink-debug"
error: failed to load manifest for dependency `index`

Caused by:
  failed to parse manifest at `/tmp/cargo-contract_E6C6EB/index/Cargo.toml`

Caused by:
  no targets specified in the manifest
  either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
```

Any comment on the workspace config?

If workspace config is OK, here is another problem: `cargo clippy -- --allow clippy::let_unit_value` covers both `contracts/` and `index/`, but we still want CI to exit on clippy warnings right?  But we can't append `-D warnings` to `cargo clippy -- --allow clippy::let_unit_value`, that will cause false alarms.

So with this config:

```yml
      - name: Run cargo clippy for index
        run: cd index/ && cargo clippy --all-targets -- -D warnings
      - name: Run cargo clippy for contracts
        run: cargo clippy -- --allow clippy::let_unit_value
```

clippy will run twice for `index/`, do you think it ok?

**Comment by tenheadedlion** [comment]
@kvinwang I tried `cargo contract build` yesterday, it's difficult to get right: https://github.com/tenheadedlion/index-contract/actions/runs/3376944607/jobs/5605276890#step:5:652

If we want this to work, we will have to compile `binaryen` on github, sounds pretty heavy burden for their machine

https://github.com/Phala-Network/oracle-workshop/blob/master/README.md?plain=1#L511-L515 shows this is kind of pit to step on. 

it seems there is no easy way to install `binaryen`: https://github.com/WebAssembly/binaryen

if we run `apt install binaryen` on ubuntu 20.04, we stand a big chance of getting an old version of `binaryen`

so what do you think, are we going to compile `binaryen` on github?

**Comment by h4x3rotab** [comment]
You can install binaryen by this:

```
cd /tmp \
    && curl -OL https://github.com/WebAssembly/binaryen/releases/download/version_110/binaryen-version_110-x86_64-linux.tar.gz \
    && tar xf binaryen-version_110-x86_64-linux.tar.gz \
    && cp binaryen-version_110/bin/* /bin/ \
    && cp binaryen-version_110/include/* /usr/include \
    && cp binaryen-version_110/lib/* /lib/ \
    && rm -rf binaryen-version_110
```

**Comment by kvinwang** [comment]
> clippy will run twice for `index/`, do you think it ok?

I think it's OK.

> But we can't append `-D warnings` to `cargo clippy -- --allow clippy::let_unit_value`, that will cause false alarms

What false alarms it would cause?

**Comment by tenheadedlion** [comment]
@kvinwang `-D warnings` throws errors:  https://gist.github.com/tenheadedlion/868f3829d8f2181fb12dc6534757bdf9

**Comment by tenheadedlion** [comment]
@kvinwang `-D warnings` throws errors:  https://gist.github.com/tenheadedlion/868f3829d8f2181fb12dc6534757bdf9

**Comment by kvinwang** [comment]
> `-D warnings` throws errors: https://gist.github.com/tenheadedlion/868f3829d8f2181fb12dc6534757bdf9

For the `unused xxx` parts, I don't think they are false warnings. They are produced by rustc, not by clippy.
For `this boolean expression can be simplified`, it should be the ink macro generating bad-styled codes. We can just allow it with `--allow clippy::nonminimal_bool` just as we did for `let_unit_value`.

**Comment by tenheadedlion** [comment]
Now we have those jobs work:

- regular checks: https://github.com/tenheadedlion/index-contract/actions/runs/3384302241
- cargo contract build in 27 minutes: https://github.com/tenheadedlion/index-contract/actions/runs/3384302239

BTW I tried https://github.com/nektos/act on my laptop, it still took 20m to finish

```
4647  11/3/2022 16:16  act
4648  11/3/2022 16:35  export HISTTIMEFORMAT='%F %T '
```

**Comment by tenheadedlion** [comment]
Here is when these jobs will be triggered:

- regular checks including `cargo test`, `cargo clippy`, `cargo fmt` will run each time you push a commit to your fork repo
- `cargo contract build` will run after you issue a pull request to the main branch, and after that, each time you append a commit to your fork repo, it will also be triggered

**Review by kvinwang — APPROVED** [review]
LGTM

**Pull request merged**
